version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]
    restart: always